MySQL 5.6.11 - Wheezy

diff --git a/debian/mysql-server-5.6.postrm b/debian/mysql-server-5.6.postrm
--- a/debian/mysql-server-5.6.postrm
+++ b/debian/mysql-server-5.6.postrm
@@ -54,9 +54,9 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
   rm -f /var/log/mysql.{log,err}{,.0,.[1234567].gz}
   rm -rf /var/log/mysql
 
-  db_input high mysql-server-5.5/postrm_remove_databases || true
+  db_input high mysql-server-5.6/postrm_remove_databases || true
   db_go || true
-  db_get mysql-server-5.5/postrm_remove_databases || true
+  db_get mysql-server-5.6/postrm_remove_databases || true
   if [ "$RET" = "true" ]; then
     # never remove the debian.cnf when the databases are still existing
     # else we ran into big trouble on the next install!
@@ -80,6 +80,6 @@ if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
 fi
 # (normally) End automatically added section
 
-# no DEBHELPER here, "update-rc.d remove" fails if mysql-server-5.5 is installed
+# no DEBHELPER here, "update-rc.d remove" fails if mysql-server-5.6 is installed
 
 exit 0
